Document: libdri2
Title: Debian libdri2 Manual
Author: <insert document author here>
Abstract: This manual describes what libdri2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libdri2/libdri2.sgml.gz

Format: postscript
Files: /usr/share/doc/libdri2/libdri2.ps.gz

Format: text
Files: /usr/share/doc/libdri2/libdri2.text.gz

Format: HTML
Index: /usr/share/doc/libdri2/html/index.html
Files: /usr/share/doc/libdri2/html/*.html
